name: PR Open Notify

on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  send-to-dingtalk:
    runs-on: ubuntu-latest
    steps:
      - name: send to dingtalk
        uses: visiky/dingtalk-release-notify@main
        with:
          DING_TALK_TOKEN: ${{ secrets.DINGDING_BOT_TOKEN }}
          notify_title: '🔥 @${{ github.event.pull_request.user.login }} 创建了 PR：${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}'
          notify_body: |
            ### 🔥 [@${{ github.event.pull_request.user.login }}](https://github.com/${{ github.event.pull_request.user.login }}) 创建了 PR：
            [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
          at_all: false # whether to ding everybody
